# Generated by Django 3.1.5 on 2022-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessDirectory', '0002_customersavedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(upload_to='static/uploads/logos/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='static/uploads/thumbs/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='image_url',
            field=models.ImageField(upload_to='static/uploads/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.ImageField(default='static/uploads/profile_photos/nophoto-male.jpg', upload_to='static/uploads/profile_photos/'),
        ),
    ]
