# Generated by Django 3.1.5 on 2022-02-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessDirectory', '0003_auto_20220226_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='addedon',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
