# Generated by Django 3.1.5 on 2022-02-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessDirectory', '0006_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.FileField(default='static/uploads/logos/no-image.png', upload_to='static/uploads/logos/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.FileField(upload_to='static/uploads/thumbs/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='image_url',
            field=models.FileField(upload_to='static/uploads/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.FileField(default='static/uploads/profile_photos/nophoto-male.jpg', upload_to='static/uploads/profile_photos/'),
        ),
    ]
