# Generated by Django 3.1.5 on 2022-02-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessDirectory', '0009_auto_20220227_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
