# Generated by Django 3.1.5 on 2022-02-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessDirectory', '0010_auto_20220228_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
