# Generated by Django 3.1.5 on 2022-03-02 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessDirectory', '0013_auto_20220302_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBusinessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('is_added', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='businessDirectory.campus')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessDirectory.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
