# Generated by Django 3.1.5 on 2022-03-02 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('businessDirectory', '0014_vendorbusinessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbusinessrequest',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
