# Generated by Django 3.1.5 on 2022-03-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessDirectory', '0015_vendorbusinessrequest_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=7.4060996, max_digits=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=6.8644553, max_digits=30),
        ),
    ]
