# Generated by Django 3.1.5 on 2022-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessDirectory', '0017_auto_20220302_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.CharField(default=6.8644553, max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.CharField(default=7.4060996, max_length=50),
        ),
    ]
